// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SDWebImageBinding;

namespace SDWebImageExample
{
	public partial class DetailViewController : UIViewController
	{
		public NSUrl ImageUrl;

		public DetailViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			ImageView.SetImageWithURL (ImageUrl, UIImage.FromBundle ("placeholder.png"));
		}
	}
}
