// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SDWebImageBinding;

namespace SDWebImageExample
{
	public partial class TableViewController : UITableViewController
	{
		private TableSource _source;
		private NSUrl _selectedUrl;
		public TableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_source = new TableSource (this);
			TableView.Source = _source;

			ClearCacheButton.Clicked += (sender, e) => {
				SDWebImageManager.SharedManager.ImageCache.ClearMemory();
				SDWebImageManager.SharedManager.ImageCache.ClearDisk();
			};
		}

		public void ShowDetailView(NSUrl url) {
			_selectedUrl = url;
			PerformSegue ("ShowDetailSegue", this);
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			if (segue.Identifier == "ShowDetailSegue") {
				var destination = segue.DestinationViewController as DetailViewController;
				if (destination != null) {
					_selectedUrl = new NSUrl(_selectedUrl.AbsoluteString.Replace ("small", "source"));
					destination.ImageUrl = _selectedUrl;
				}
			}
			base.PrepareForSegue (segue, sender);

		}
	}
}
